const InputsData = [
    {
        id: 0,
        name: "flyingfrom",
        type: "text",
        heading: "Flying From",
        select: true,
        insideData: [
            {
                id: 1,
                name: "Afghanistan",
                population: 38928346,
                land_area: 652230,
                density: 59.6,
                capital: "Kabul",
                currency: "Afghan afghani",
                flag: "https://fakeimg.pl/500x300/ff6600",
            },
            {
                id: 2,
                name: "Albania",
                population: 2877797,
                land_area: 28748,
                density: 100.1,
                capital: "Tirana",
                currency: "Albanian lek",
                flag: "https://fakeimg.pl/500x300/ff9900",
            },
            {
                id: 3,
                name: "Algeria",
                population: 43851043,
                land_area: 2381741,
                density: 18.4,
                capital: "Algiers",
                currency: "Algerian dinar",
                flag: "https://fakeimg.pl/500x300/ffcc00",
            },
            {
                id: 4,
                name: "Andorra",
                population: 77265,
                land_area: 468,
                density: 164.8,
                capital: "Andorra la Vella",
                currency: "Euro",
                flag: "https://fakeimg.pl/500x300/ffff00",
            },
            {
                id: 5,
                name: "Angola",
                population: 32866272,
                land_area: 1246700,
                density: 26.4,
                capital: "Luanda",
                currency: "Angolan kwanza",
                flag: "https://fakeimg.pl/500x300/00ff00",
            },
            {
                id: 6,
                name: "Antigua and Barbuda",
                population: 97928,
                land_area: 443,
                density: 220.8,
                capital: "Saint John's",
                currency: "East Caribbean dollar",
                flag: "https://fakeimg.pl/500x300/00ff66",
            },
            {
                id: 7,
                name: "Argentina",
                population: 45195777,
                land_area: 2780400,
                density: 16.3,
                capital: "Buenos Aires",
                currency: "Argentine peso",
                flag: "https://fakeimg.pl/500x300/6600cc",
            },
            {
                id: 8,
                name: "Armenia",
                population: 2963234,
                land_area: 29743,
                density: 99.6,
                capital: "Yerevan",
                currency: "Armenian dram",
                flag: "https://fakeimg.pl/500x300/9900cc",
            },
            {
                id: 9,
                name: "Australia",
                population: 25788204,
                land_area: 7692024,
                density: 3.4,
                capital: "Canberra",
                currency: "Australian dollar",
                flag: "https://fakeimg.pl/500x300/cc00cc",
            },
            {
                id: 10,
                name: "Austria",
                population: 8994944,
                land_area: 83871,
                density: 107.3,
                capital: "Vienna",
                currency: "Euro",
                flag: "https://fakeimg.pl/500x300/ff00cc",
            },
            {
                id: 11,
                name: "Azerbaijan",
                population: 10139175,
                land_area: 86600,
                density: 117.1,
                capital: "Baku",
                currency: "Azerbaijani manat",
                flag: "https://fakeimg.pl/500x300/00ccff",
            },
            {
                id: 12,
                name: "Bahamas",
                population: 396913,
                land_area: 13880,
                density: 28.6,
                capital: "Nassau",
                currency: "Bahamian dollar",
                flag: "https://fakeimg.pl/500x300/00ffcc",
            },
            {
                id: 13,
                name: "Bahrain",
                population: 1701575,
                land_area: 765,
                density: 2228.6,
                capital: "Manama",
                currency: "Bahraini dinar",
                flag: "https://fakeimg.pl/500x300/ffcc00",
            },
            {
                id: 14,
                name: "Bangladesh",
                population: 166303498,
                land_area: 148460,
                density: 1119.1,
                capital: "Dhaka",
                currency: "Bangladeshi taka",
                flag: "https://fakeimg.pl/500x300/660066",
            },
            {
                id: 15,
                name: "Barbados",
                population: 287025,
                land_area: 430,
                density: 668.7,
                capital: "Bridgetown",
                currency: "Barbadian dollar",
                flag: "https://fakeimg.pl/500x300/660099",
            },
        ],
    },
    {
        id: 1,
        name: "flyingto",
        type: "text",
        heading: "Flying To",
        select: true,
        insideData: [
            {
                id: 1,
                name: "Paris",
                population: 38928346,
                land_area: 652230,
                density: 59.6,
                capital: "Kabul",
                currency: "Afghan afghani",
                flag: "https://fakeimg.pl/500x300/ff6600",
            },
            {
                id: 2,
                name: "Albania",
                population: 2877797,
                land_area: 28748,
                density: 100.1,
                capital: "Tirana",
                currency: "Albanian lek",
                flag: "https://fakeimg.pl/500x300/ff9900",
            },
            {
                id: 3,
                name: "Algeria",
                population: 43851043,
                land_area: 2381741,
                density: 18.4,
                capital: "Algiers",
                currency: "Algerian dinar",
                flag: "https://fakeimg.pl/500x300/ffcc00",
            },
            {
                id: 4,
                name: "Andorra",
                population: 77265,
                land_area: 468,
                density: 164.8,
                capital: "Andorra la Vella",
                currency: "Euro",
                flag: "https://fakeimg.pl/500x300/ffff00",
            },
            {
                id: 5,
                name: "Angola",
                population: 32866272,
                land_area: 1246700,
                density: 26.4,
                capital: "Luanda",
                currency: "Angolan kwanza",
                flag: "https://fakeimg.pl/500x300/00ff00",
            },
            {
                id: 6,
                name: "Antigua and Barbuda",
                population: 97928,
                land_area: 443,
                density: 220.8,
                capital: "Saint John's",
                currency: "East Caribbean dollar",
                flag: "https://fakeimg.pl/500x300/00ff66",
            },
            {
                id: 7,
                name: "Argentina",
                population: 45195777,
                land_area: 2780400,
                density: 16.3,
                capital: "Buenos Aires",
                currency: "Argentine peso",
                flag: "https://fakeimg.pl/500x300/6600cc",
            },
            {
                id: 8,
                name: "Armenia",
                population: 2963234,
                land_area: 29743,
                density: 99.6,
                capital: "Yerevan",
                currency: "Armenian dram",
                flag: "https://fakeimg.pl/500x300/9900cc",
            },
            {
                id: 9,
                name: "Australia",
                population: 25788204,
                land_area: 7692024,
                density: 3.4,
                capital: "Canberra",
                currency: "Australian dollar",
                flag: "https://fakeimg.pl/500x300/cc00cc",
            },
            {
                id: 10,
                name: "Austria",
                population: 8994944,
                land_area: 83871,
                density: 107.3,
                capital: "Vienna",
                currency: "Euro",
                flag: "https://fakeimg.pl/500x300/ff00cc",
            },
            {
                id: 11,
                name: "Azerbaijan",
                population: 10139175,
                land_area: 86600,
                density: 117.1,
                capital: "Baku",
                currency: "Azerbaijani manat",
                flag: "https://fakeimg.pl/500x300/00ccff",
            },
            {
                id: 12,
                name: "Bahamas",
                population: 396913,
                land_area: 13880,
                density: 28.6,
                capital: "Nassau",
                currency: "Bahamian dollar",
                flag: "https://fakeimg.pl/500x300/00ffcc",
            },
            {
                id: 13,
                name: "Bahrain",
                population: 1701575,
                land_area: 765,
                density: 2228.6,
                capital: "Manama",
                currency: "Bahraini dinar",
                flag: "https://fakeimg.pl/500x300/ffcc00",
            },
            {
                id: 14,
                name: "Bangladesh",
                population: 166303498,
                land_area: 148460,
                density: 1119.1,
                capital: "Dhaka",
                currency: "Bangladeshi taka",
                flag: "https://fakeimg.pl/500x300/660066",
            },
            {
                id: 15,
                name: "Barbados",
                population: 287025,
                land_area: 430,
                density: 668.7,
                capital: "Bridgetown",
                currency: "Barbadian dollar",
                flag: "https://fakeimg.pl/500x300/660099",
            },
        ],
    },
    {
        id: 2,
        name: "fromdate",
        type: "date",
        heading: "From Date",
    },
    {
        id: 3,
        name: "todate",
        type: "date",
        heading: "From Date",
    },
    {
        id: 4,
        name: "budget",
        type: "number",
        heading: "Budget",
        colSpan: true,
    },

];
export default InputsData